services:
  db:
    build: ./db
    image: db_webcau:1
    container_name: mysql_db
    ports:
      - 3306:3306
    networks:
      - webcau_network
  app:
    build: ./app
    image: app_webcau:2
    container_name: app_frontend
    ports:
      - 5173:5173
    volumes:
      - ./app:/app
    depends_on:
      - auth
    networks:
      - webcau_network
  auth:
    build: ./auth
    image: auth_webcau:1
    container_name: auth_backend
    ports:
      - 8081:8081
    volumes:
      - ./auth:/app
    depends_on:
      - db
    networks:
      - webcau_network
  server:
    build: ./server
    image: server_webcau:1
    container_name: server_backend
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    depends_on:
      - app
    networks:
      - webcau_network

networks:
  webcau_network:
    driver: bridge